FROM node:23-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

EXPOSE ${WEB_PORT}

#CMD ["npm", "run", "dev", "--", "--port", "${WEB_PORT}"]
CMD ["sh", "-c", "npm run dev -- --port ${WEB_PORT}"]