{
 "title": "Grok1",
 "tags": [
  "nodejs",
  "nestjs",
  "prometheus"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "label": "Job", "query": { "query": "label_values(job)" } },
   { "name": "node", "label": "Node", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  { "title": "Quick Node.js App Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Node.js CPU Usage by Type (24h)",
   "type": "bargauge",
   "description": "Total CPU usage of the Node.js process over 24h, split by user and system time",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(process_cpu_user_seconds_total{instance=\"$node\",job=\"$job\"}[1d])",
     "legendFormat": "User CPU"
    },
    {
     "expr": "increase(process_cpu_system_seconds_total{instance=\"$node\",job=\"$job\"}[1d])",
     "legendFormat": "System CPU"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Node.js process uptime",
   "gridPos": { "h": 5, "w": 2, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{instance=\"$node\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Node.js Process CPU Usage",
   "type": "gauge",
   "description": "CPU usage of the Node.js process",
   "gridPos": { "h": 5, "w": 3, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{instance=\"$node\",job=\"$job\"}[5m]) * 100"
    }
   ]
  },
  {
   "title": "Process Memory Metrics",
   "type": "gauge",
   "description": "Current memory usage metrics of the Node.js process",
   "gridPos": { "h": 5, "w": 7, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Virtual Memory"
    },
    {
     "expr": "process_heap_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Heap"
    },
    {
     "expr": "process_resident_memory_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Resident Memory"
    }
   ]
  },
  {
   "title": "External Memory Usage",
   "type": "gauge",
   "description": "Current external memory used by Node.js",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nodejs_external_memory_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "External Memory"
    }
   ]
  },
  {
   "title": "Node.js Active Handles",
   "type": "gauge",
   "description": "Active handles in the Node.js process",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nodejs_active_handles_total{instance=\"$node\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "gauge",
   "description": "Current number of open file descriptors vs maximum allowed",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_open_fds{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Open FDs"
    },
    { "legendFormat": "Max FDs" }
   ]
  },
  { "title": "Detailed NodeJS metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Event Loop Lag Statistics",
   "type": "stat",
   "description": "Current statistics of Node.js event loop lag",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nodejs_eventloop_lag_min_seconds{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Min"
    },
    {
     "expr": "nodejs_eventloop_lag_max_seconds{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "nodejs_eventloop_lag_mean_seconds{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Mean"
    },
    {
     "expr": "nodejs_eventloop_lag_p50_seconds{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "P50"
    },
    {
     "expr": "nodejs_eventloop_lag_p90_seconds{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "P90"
    },
    {
     "expr": "nodejs_eventloop_lag_p99_seconds{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "Node.js Event Loop Lag",
   "type": "timeseries",
   "description": "Node.js event loop lag in seconds",
   "gridPos": { "h": 8, "w": 11, "x": 3, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "nodejs_eventloop_lag_seconds{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Event Loop Lag"
    }
   ]
  },
  {
   "title": "Node.js Heap Usage",
   "type": "timeseries",
   "description": "Node.js heap memory usage",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "nodejs_heap_size_used_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Heap Used"
    },
    {
     "expr": "nodejs_heap_size_total_bytes{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Heap Total"
    }
   ]
  },
  { "title": "Node.js Application Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "HTTP Requests Rate",
   "type": "timeseries",
   "description": "Total HTTP requests by method, path, and status",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(http_requests_total{instance=\"$node\",job=\"$job\",path!=\"/metrics\"}[5m])",
     "legendFormat": "{{method}} {{path}} {{status}}"
    }
   ]
  },
  {
   "title": "Kafka Events Rate",
   "type": "timeseries",
   "description": "Total Kafka event messages processed",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(event_messages_total{instance=\"$node\",job=\"$job\"}[5m])",
     "legendFormat": "{{event_type}}"
    }
   ]
  },
  {
   "title": "HTTP Requests Today",
   "type": "timeseries",
   "description": "Total HTTP requests by method, path, and status",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(http_requests_total{instance=\"$node\",job=\"$job\",path!=\"/metrics\"}[1d])",
     "legendFormat": "{{method}} {{path}} {{status}}"
    }
   ]
  },
  {
   "title": "Kafka Events Today",
   "type": "timeseries",
   "description": "Total Kafka event messages processed",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(event_messages_total{instance=\"$node\",job=\"$job\"}[1d])",
     "legendFormat": "{{event_type}}"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Scan logs",
   "type": "logs",
   "description": "System logs collected by Promtail",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "{service=~\"scan\"}",
     "maxLines": 1000
    }
   ]
  },
  {
   "title": "Api-gateway logs",
   "type": "logs",
   "description": "System logs collected by Promtail",
   "gridPos": { "h": 11, "w": 11, "x": 13, "y": 33 },
   "targets": [
    {
     "expr": "{service=~\"api-gateway\"}",
     "maxLines": 1000
    }
   ]
  },
  {
   "title": "Product-analyzer logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "{service=~\"product-analyzer\"}",
     "maxLines": 1000
    }
   ]
  },
  {
   "title": "All errors",
   "type": "logs",
   "gridPos": { "h": 23, "w": 11, "x": 13, "y": 44 },
   "targets": [
    {
     "expr": "{service=~\"api-gateway|scan|product-analyzer|ingredients-recognition\", stream=\"stderr\"}",
     "maxLines": 1000
    }
   ]
  },
  {
   "title": "Ingredients-recognition logs",
   "type": "logs",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 54 },
   "targets": [
    {
     "expr": "{service=~\"ingredients-recognition\"}",
     "maxLines": 1000
    }
   ]
  }
 ]
}