services:
  promtail:
    image: grafana/promtail:3.4.3
    container_name: promtail
    ports:
      - "9080:9080"
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./promtail-config.yaml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    privileged: true
    attach: false

  loki:
    image: grafana/loki:3.4.3
    container_name: loki
    ports:
      - "9070:9070"
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
    attach: false

  prometheus:
    image: prom/prometheus:v3.2.1
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheusdata:/prometheus
    attach: false

  grafana:
    image: grafana/grafana:9.1.7
    container_name: grafana
    ports:
      - "9000:9000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_HTTP_PORT=9000
    volumes:
      - ./grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - grafanadata:/var/lib/grafana
    attach: false

volumes:
  grafanadata:
  prometheusdata: