server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
#        filters:
#          - name: label
#            values: [
#              "com.docker.compose.service=api-gateway",
#              "com.docker.compose.service=scan",
#              "com.docker.compose.service=product-analyzer",
#              "com.docker.compose.service=ingredients-recognition"
#            ]
    relabel_configs:
      - source_labels: [__meta_docker_container_name]
        target_label: container
      - source_labels: [__meta_docker_container_label_com_docker_compose_service]
        target_label: service
      - source_labels: [__meta_docker_container_log_stream]
        target_label: stream

#scrape_configs:
#  - job_name: docker-logs
#    static_configs:
#      - targets:
#          - localhost
#        labels:
#          job: docker-logs
#          __path__: /var/lib/docker/containers/*/*log
#
#    pipeline_stages:
#
#      - json:
#          expressions:
#            stream: stream
#            attrs: attrs
#            tag: attrs.tag
#
#      - regex:
#          expression: (?P<image_name>(?:[^|]*[^|])).(?P<container_name>(?:[^|]*[^|])).(?P<image_id>(?:[^|]*[^|])).(?P<container_id>(?:[^|]*[^|]))
#          source: "tag"
#
#      - labels:
#          tag:
#          image_name:
#          container_name:
