global:
  scrape_interval: 3s

scrape_configs:
  - job_name: "microservices"
    metrics_path: /metrics
    static_configs:
      - targets: [
        "api-gateway:3000",
        "scan:3020",
        "product-analyzer:3030",
        "ingredients-recognition:3040",
      ]
