FROM node:23-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

# Run in development mode
CMD cd apps/product-analyzer && \
    npx prisma generate && \
    npx prisma migrate deploy && \
    cd ../.. && \
    npx prisma db seed && \
    npm run start:dev product-analyzer