FROM node:23-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

# Run in development mode
#CMD ["sh", "-c", "npx prisma generate && npx prisma migrate deploy"]
#CMD ["npm", "run", "start:dev", "scan"]
CMD cd apps/scan && \
    npx prisma generate && \
    npx prisma migrate deploy && \
    npm run start:dev scan